# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GarrisonBuilder.ui'
#
# Created: Thu Jul 12 22:45:39 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MapEditor(object):
    def setupUi(self, MapEditor):
        MapEditor.setObjectName(_fromUtf8("MapEditor"))
        MapEditor.resize(836, 601)
        MapEditor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MapEditor)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea = QtGui.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 389, 457))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mappreview = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mappreview.sizePolicy().hasHeightForWidth())
        self.mappreview.setSizePolicy(sizePolicy)
        self.mappreview.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mappreview.setAlignment(QtCore.Qt.AlignCenter)
        self.mappreview.setObjectName(_fromUtf8("mappreview"))
        self.gridLayout_2.addWidget(self.mappreview, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.reset = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset.sizePolicy().hasHeightForWidth())
        self.reset.setSizePolicy(sizePolicy)
        self.reset.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reset.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.reset.setAutoFillBackground(False)
        self.reset.setObjectName(_fromUtf8("reset"))
        self.horizontalLayout_2.addWidget(self.reset)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.enlarge = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enlarge.sizePolicy().hasHeightForWidth())
        self.enlarge.setSizePolicy(sizePolicy)
        self.enlarge.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.enlarge.setDefault(False)
        self.enlarge.setFlat(False)
        self.enlarge.setObjectName(_fromUtf8("enlarge"))
        self.verticalLayout_4.addWidget(self.enlarge)
        self.shrink = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shrink.sizePolicy().hasHeightForWidth())
        self.shrink.setSizePolicy(sizePolicy)
        self.shrink.setObjectName(_fromUtf8("shrink"))
        self.verticalLayout_4.addWidget(self.shrink)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.comboBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(6, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboBox)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.scrollArea_2 = QtGui.QScrollArea(self.verticalLayoutWidget_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 397, 510))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setGeometry(QtCore.QRect(25, 180, 121, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MapEditor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MapEditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 836, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MapEditor.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MapEditor)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MapEditor.setStatusBar(self.statusBar)
        self.actionNew = QtGui.QAction(MapEditor)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MapEditor)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MapEditor)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MapEditor)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionChange_Map_Type = QtGui.QAction(MapEditor)
        self.actionChange_Map_Type.setObjectName(_fromUtf8("actionChange_Map_Type"))
        self.actionSave_Entitites = QtGui.QAction(MapEditor)
        self.actionSave_Entitites.setObjectName(_fromUtf8("actionSave_Entitites"))
        self.actionSave_Maskdata = QtGui.QAction(MapEditor)
        self.actionSave_Maskdata.setObjectName(_fromUtf8("actionSave_Maskdata"))
        self.actionQuit = QtGui.QAction(MapEditor)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionDock_Widget = QtGui.QAction(MapEditor)
        self.actionDock_Widget.setObjectName(_fromUtf8("actionDock_Widget"))
        self.actionCopy = QtGui.QAction(MapEditor)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MapEditor)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionWallmask = QtGui.QAction(MapEditor)
        self.actionWallmask.setObjectName(_fromUtf8("actionWallmask"))
        self.actionEntities = QtGui.QAction(MapEditor)
        self.actionEntities.setObjectName(_fromUtf8("actionEntities"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuView.addAction(self.actionDock_Widget)
        self.menuView.addAction(self.actionWallmask)
        self.menuView.addAction(self.actionEntities)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MapEditor)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MapEditor.close)
        QtCore.QMetaObject.connectSlotsByName(MapEditor)

    def retranslateUi(self, MapEditor):
        MapEditor.setWindowTitle(QtGui.QApplication.translate("MapEditor", "Garrison Builder", None, QtGui.QApplication.UnicodeUTF8))
        self.mappreview.setText(QtGui.QApplication.translate("MapEditor", "Please Load Map", None, QtGui.QApplication.UnicodeUTF8))
        self.reset.setWhatsThis(QtGui.QApplication.translate("MapEditor", "<html><head/><body><p>hello</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.reset.setText(QtGui.QApplication.translate("MapEditor", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.enlarge.setToolTip(QtGui.QApplication.translate("MapEditor", "<html><head/><body><p>lopl</p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.enlarge.setText(QtGui.QApplication.translate("MapEditor", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.shrink.setText(QtGui.QApplication.translate("MapEditor", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setStatusTip(QtGui.QApplication.translate("MapEditor", "Select the Game Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MapEditor", "CTF", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MapEditor", "CP", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MapEditor", "Arena", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MapEditor", "Dkoth", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("MapEditor", "Koth", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("MapEditor", "Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MapEditor", "Please Load Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MapEditor", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MapEditor", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MapEditor", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MapEditor", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MapEditor", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MapEditor", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MapEditor", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_Map_Type.setText(QtGui.QApplication.translate("MapEditor", "Change Map Type", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Entitites.setText(QtGui.QApplication.translate("MapEditor", "Save Entitites", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Maskdata.setText(QtGui.QApplication.translate("MapEditor", "Save Maskdata", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MapEditor", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDock_Widget.setText(QtGui.QApplication.translate("MapEditor", "Dock Widget", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MapEditor", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("MapEditor", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MapEditor", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("MapEditor", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWallmask.setText(QtGui.QApplication.translate("MapEditor", "Wallmask", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEntities.setText(QtGui.QApplication.translate("MapEditor", "Entities", None, QtGui.QApplication.UnicodeUTF8))

