{
createButton(loadExisMap);
createButton(CreateNewMap);
createButton(testMap);
createButton(loadBG);
createButton(unloadBG);
createButton(loadWalkmask);
createButton(unloadWalkmask);
createButton(loadEntities);
createButton(unloadEntities);
createButton(saveEntities);
createButton(embedLevelDataInPNG);
createButton(editBG);
createButton(editWM);
createButton(testMap);
//createButton(customClear);
createToolButton(moveTool);
createToggleButton(bgVisible, true);
createToggleButton(walkmaskVisible, false);
createToggleButton(snapToGrid, true);
createToggleButton(gridVisible, false);
createToolButton(redspawn);
createToolButton(bluespawn);
createToolButton(medCabinet);
createToolButton(redteamgate);
createToolButton(redteamgate2);
createToolButton(blueteamgate);
createToolButton(blueteamgate2);
createToolButton(bulletwall);
createToolButton(bulletwall_horizontal);
createToolButton(playerwall);
createToolButton(playerwall_horizontal);
createToolButton(killbox);
createToolButton(fragbox);
createToolButton(spawnroom);
createToolButton(MoveBoxUp);
createToolButton(MoveBoxDown);
createToolButton(MoveBoxLeft);
createToolButton(MoveBoxRight);
createToolButton(leftdoor);
createToolButton(rightdoor);
}
