{
    createToolButton(controlPoint1);
    createToolButton(controlPoint2);
    createToolButton(controlPoint3);
    createToolButton(controlPoint4);
    createToolButton(controlPoint5);
    createToolButton(CapturePoint);
    createToolButton(redspawn1)
    createToolButton(redspawn2)
    createToolButton(redspawn3)
    createToolButton(redspawn4)
    createToolButton(bluespawn1)
    createToolButton(bluespawn2)
    createToolButton(bluespawn3)
    createToolButton(bluespawn4)
 }
